import org.gradle.jvm.toolchain.JavaLanguageVersion

plugins {
	id 'java'
	id 'maven-publish'
	id 'idea'
	id 'eclipse'
	id 'dev.architectury.loom' version '1.9-SNAPSHOT'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

loom {
	runs {
		data {
			data()
		}
	}
	//accessWidenerPath = file("src/main/resources/traverse.accesswidener")
	forge {
		convertAccessWideners = true
		extraAccessWideners.add("traverse.accesswidener")
		dataGen {
			mod "traverse"
		}
	}
}

group = project.maven_group

configurations {
	dev {
		canBeResolved = false
		canBeConsumed = true
	}
}

repositories {
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/'
	}

	// TerraBlender
	maven {
		url = 'https://maven.minecraftforge.net/'
	}
	maven {  url = "https://maven.blamejared.com/"}
	maven { url 'https://jitpack.io' }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"

	forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

	//includeMod "terraform-api", "com.terraformersmc.terraform-api:terraform-biome-remapper-api-v1:${project.terraform_biome_remapper_api_version}"
	modImplementation include("dev.trinsdar:terraform-config-api-v1:${project.terraform_version}")
	modImplementation include("dev.trinsdar:terraform-surfaces-api-v1:${project.terraform_version}")
	modImplementation include("dev.trinsdar:terraform-tree-api-v1:${project.terraform_version}")
	modImplementation include("dev.trinsdar:terraform-wood-api-v1:${project.terraform_version}")
	modImplementation include("dev.trinsdar:terraform-utils-v1:${project.terraform_version}")

	modImplementation "com.github.glitchfiend:TerraBlender-forge:${terrablender_version}"
}

jar {
	archiveClassifier.set "dev"
}

afterEvaluate {
	processResources {
		inputs.property "version", project.version

		filesMatching("META-INF/mods.toml") {
			expand "version": project.version
		}
	}
}
